##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://etownhighlibrary.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /etownstorycorps 
# location of code, the full url to your github repository
source-code: https://etownhighlibrary.github.io/etownstorycorps

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Etown StoryCorps
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Interviews recorded by students in Professor Suzy Biever-Grodzinski's ENG 100 course
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: In fall of 2019, English 100 students at Elizabethtown College began the journey into collecting students’ digital stories to add to various local, national and international archives through StoryCorps. Since this first semester, each student in Suzanne Biever-Grodzinski’s English 100 course has created their own contribution to the digital StoryCorps quilt. 
StoryCorps is an organization whose mission is “to preserve and share humanity’s stories in order to build connections between people and create a more just and compassionate world.” StoryCorps allows individuals to record stories, to record interviews with other people, with the intent of helping them connect, understand, and be compassionate towards one another. These digital stories are then added not only to StoryCorps’s online archive, but to the Library of Congress for future generations to reference, appreciate, and learn from. 
At the beginning of each semester, students receive the following prompt in their English 100 course:
“Right now, you should start thinking of someone in your life whom you might want to interview. Who inspires you? Who do you want to know more about? Who do you want to ask that burning question to? The one you’ll regret not asking? What do you want to ask them about: religion? race? music? forgiveness?”
The prompt is intended to give students permission to enter a space of communication, to use their own style of discourse and their own curiosity to learn more about another person and the world. Since the start of the English 100 StoryCorps experience, these stories have also started to accumulate into this digital archive with Elizabethtown College’s High Library. The goal of the project is not only to introduce students to the real-life, practical applications of reading and writing, but to connect individuals in the profoundly human experience of storytelling.

# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: pennimans

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: etown-storycorps 

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
